//&>/dev/null;x="${0%.*}";[ ! "$x" -ot "$0" ]||(rm -f "$x";g++ -o "$x" "$0")&&"$x" $*;exit
// =====================================================================================
// 
//       Filename:  PracticalSocket.H
// 
//    Description:  
// 
//        Version:  1.0
//        Created:  11/11/2011 05:14:05 PM
//       Revision:  none
//       Compiler:  g++
// 
//         Author:  Philip.Young (Cxy), yangcongxi@cdeledu.com
//        Company:  CDEL
// 
// =====================================================================================


